version: '3.9'

services:
  sdc:
    build:
      context: .
      dockerfile: dockerfile
    deploy:
      replicas: 5

  nginx:
    image: nginx
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sdc
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

