version: '3.9'

services:
  sdcserver:
    build:
      context: .
      dockerfile: dockerfile
    deploy:
      replicas: 5
    ports:
      - 4000:4000

  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - sdcserver
    ports:
      - 8080:8080
